name: implantando-no-servidor
run-name: Implantando o código em servidor local usando Cloudflare.
on: [push]
jobs:
  implantando-no-servidor:
    runs-on: ubuntu-latest
    steps:
      ######################################################################
      #### Esse cara funciona!
      ######################################################################
      # - name: Executa o comando SSH para entrar e fazer o que for necessário
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     port: ${{ secrets.SSH_PORT }}
      #     script: |
      #       cd ${{ secrets.SSH_TARGET}}
      #       git pull

      - name: Conectar usando o Cloudflare como porta de entrada
        uses: npgy/cloudflared-ssh-action@v2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          # port: ${{ secrets.PORT }}
          commands: cd "${{ secrets.SSH_TARGET }}"; podman-compose down; sleep 5; git pull; podman-compose up -d; ls -la;

