name: implantando-no-servidor
run-name: Implantando o código no servidor.
on: [push]
jobs:
  implantando-no-servidor:
    runs-on: ubuntu-latest
    steps:
      ######################################################################
      #### Esse cara funciona!
      ######################################################################
      - name: Executa o comando SSH para entrar e fazer o que for necessário
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.SSH_TARGET}}
            git pull