name: implantando-no-servidor
run-name: ${{ github.actor }} implantando no servidor.
on: [push]
jobs:
  implantando-no-servidor:
    runs-on: ubuntu-latest
    steps:
        - name: Install SSH Key
          uses: shimataro/ssh-key-action@v2
          with:
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
        - name: Adding Known Hosts
          run: ssh-keyscan -p 22221 ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        - name: Enviar os arquivos para o destino
          # run: rsync -avz ./dist/ ${{ secrets.SSH_USER}}@${{ secrets.SSH_HOST}}:~/teste/ -e 'ssh -p ${{ secrets.SSH_PORT}}'
          run: ls -la ./